// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKLgRYEDTvS2Iq0yQdlbuGdBVrCr5_vtc',
    appId: '1:105438638257:web:4689a1a42c9c3440d73290',
    messagingSenderId: '105438638257',
    projectId: 'counter-2a631',
    authDomain: 'counter-2a631.firebaseapp.com',
    databaseURL: 'https://counter-2a631-default-rtdb.firebaseio.com',
    storageBucket: 'counter-2a631.appspot.com',
    measurementId: 'G-LKVFJEHKLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLbvWfAVJU35S13vHQjV9nG8Rg9VrErLk',
    appId: '1:105438638257:android:9e5cbf9932fb220bd73290',
    messagingSenderId: '105438638257',
    projectId: 'counter-2a631',
    databaseURL: 'https://counter-2a631-default-rtdb.firebaseio.com',
    storageBucket: 'counter-2a631.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ87JxKnaobUXhxJqDvREXe1U89kmnLRc',
    appId: '1:105438638257:ios:173889a6d8436b6bd73290',
    messagingSenderId: '105438638257',
    projectId: 'counter-2a631',
    databaseURL: 'https://counter-2a631-default-rtdb.firebaseio.com',
    storageBucket: 'counter-2a631.appspot.com',
    iosBundleId: 'com.noelle.counter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ87JxKnaobUXhxJqDvREXe1U89kmnLRc',
    appId: '1:105438638257:ios:173889a6d8436b6bd73290',
    messagingSenderId: '105438638257',
    projectId: 'counter-2a631',
    databaseURL: 'https://counter-2a631-default-rtdb.firebaseio.com',
    storageBucket: 'counter-2a631.appspot.com',
    iosBundleId: 'com.noelle.counter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKLgRYEDTvS2Iq0yQdlbuGdBVrCr5_vtc',
    appId: '1:105438638257:web:30f7aaf35ab1483ed73290',
    messagingSenderId: '105438638257',
    projectId: 'counter-2a631',
    authDomain: 'counter-2a631.firebaseapp.com',
    databaseURL: 'https://counter-2a631-default-rtdb.firebaseio.com',
    storageBucket: 'counter-2a631.appspot.com',
    measurementId: 'G-6XD6K7WFBL',
  );
}
